# Generated by Django 5.2 on 2025-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_servicerequest_delete_harsh'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
