# Generated by Django 5.2.3 on 2025-06-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
    ]
